import { Product } from './product';

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 220,
    stock: 14,
    category: 'manga',
  },
  {
    id: 2,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 201,
    stock: 127,
    category: 'manga',
  },
  {
    id: 3,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 30,
    stock: 117,
    category: 'manga',
  },
  {
    id: 4,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 22,
    stock: 7,
    category: 'manga',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 23,
    stock: 16,
    category: 'manga',
  },
  {
    id: 2,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 40,
    stock: 14,
    category: 'manga',
  },
  {
    id: 3,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 31,
    stock: 128,
    category: 'manga',
  },
  {
    id: 4,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 59,
    stock: 118,
    category: 'manga',
  },
  {
    id: 5,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 80,
    stock: 18,
    category: 'manga',
  },
  {
    id: 6,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 30,
    stock: 8,
    category: 'manga',
  },
  {
    id: 7,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 450,
    stock: 1,
    category: 'manga',
  },
  {
    id: 8,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 30,
    stock: 2,
    category: 'manga',
  },
  {
    id: 9,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 45,
    stock: 28,
    category: 'manga',
  },
  {
    id: 10,
    name: 'Dr Nice',
    description: 'Lorem ipsum',
    price: 80,
    stock: 8,
    category: 'manga',
  },
];
